// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0--rc2
// source: kitty_user_auth.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenIntrospectionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIntrospectionReq) Reset() {
	*x = TokenIntrospectionReq{}
	mi := &file_kitty_user_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIntrospectionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIntrospectionReq) ProtoMessage() {}

func (x *TokenIntrospectionReq) ProtoReflect() protoreflect.Message {
	mi := &file_kitty_user_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIntrospectionReq.ProtoReflect.Descriptor instead.
func (*TokenIntrospectionReq) Descriptor() ([]byte, []int) {
	return file_kitty_user_auth_proto_rawDescGZIP(), []int{0}
}

func (x *TokenIntrospectionReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenIntrospectionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenIntrospectionResp) Reset() {
	*x = TokenIntrospectionResp{}
	mi := &file_kitty_user_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenIntrospectionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenIntrospectionResp) ProtoMessage() {}

func (x *TokenIntrospectionResp) ProtoReflect() protoreflect.Message {
	mi := &file_kitty_user_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenIntrospectionResp.ProtoReflect.Descriptor instead.
func (*TokenIntrospectionResp) Descriptor() ([]byte, []int) {
	return file_kitty_user_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenIntrospectionResp) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type SaTokenDaoGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaTokenDaoGetReq) Reset() {
	*x = SaTokenDaoGetReq{}
	mi := &file_kitty_user_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaTokenDaoGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaTokenDaoGetReq) ProtoMessage() {}

func (x *SaTokenDaoGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kitty_user_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaTokenDaoGetReq.ProtoReflect.Descriptor instead.
func (*SaTokenDaoGetReq) Descriptor() ([]byte, []int) {
	return file_kitty_user_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SaTokenDaoGetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SaTokenDaoGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaTokenDaoGetResp) Reset() {
	*x = SaTokenDaoGetResp{}
	mi := &file_kitty_user_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaTokenDaoGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaTokenDaoGetResp) ProtoMessage() {}

func (x *SaTokenDaoGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_kitty_user_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaTokenDaoGetResp.ProtoReflect.Descriptor instead.
func (*SaTokenDaoGetResp) Descriptor() ([]byte, []int) {
	return file_kitty_user_auth_proto_rawDescGZIP(), []int{3}
}

func (x *SaTokenDaoGetResp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SaTokenDaoTimeOutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaTokenDaoTimeOutReq) Reset() {
	*x = SaTokenDaoTimeOutReq{}
	mi := &file_kitty_user_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaTokenDaoTimeOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaTokenDaoTimeOutReq) ProtoMessage() {}

func (x *SaTokenDaoTimeOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_kitty_user_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaTokenDaoTimeOutReq.ProtoReflect.Descriptor instead.
func (*SaTokenDaoTimeOutReq) Descriptor() ([]byte, []int) {
	return file_kitty_user_auth_proto_rawDescGZIP(), []int{4}
}

func (x *SaTokenDaoTimeOutReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SaTokenDaoTimeOutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeOut       int64                  `protobuf:"varint,1,opt,name=timeOut,proto3" json:"timeOut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaTokenDaoTimeOutResp) Reset() {
	*x = SaTokenDaoTimeOutResp{}
	mi := &file_kitty_user_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaTokenDaoTimeOutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaTokenDaoTimeOutResp) ProtoMessage() {}

func (x *SaTokenDaoTimeOutResp) ProtoReflect() protoreflect.Message {
	mi := &file_kitty_user_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaTokenDaoTimeOutResp.ProtoReflect.Descriptor instead.
func (*SaTokenDaoTimeOutResp) Descriptor() ([]byte, []int) {
	return file_kitty_user_auth_proto_rawDescGZIP(), []int{5}
}

func (x *SaTokenDaoTimeOutResp) GetTimeOut() int64 {
	if x != nil {
		return x.TimeOut
	}
	return 0
}

var File_kitty_user_auth_proto protoreflect.FileDescriptor

const file_kitty_user_auth_proto_rawDesc = "" +
	"\n" +
	"\x15kitty_user_auth.proto\x12\x1bicu.jiapeng.kitty.user.grpc\"-\n" +
	"\x15TokenIntrospectionReq\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\".\n" +
	"\x16TokenIntrospectionResp\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\"$\n" +
	"\x10SaTokenDaoGetReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\")\n" +
	"\x11SaTokenDaoGetResp\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"(\n" +
	"\x14SaTokenDaoTimeOutReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"1\n" +
	"\x15SaTokenDaoTimeOutResp\x12\x18\n" +
	"\atimeOut\x18\x01 \x01(\x03R\atimeOut2\xfe\x02\n" +
	"\vAuthService\x12\x7f\n" +
	"\x12TokenIntrospection\x122.icu.jiapeng.kitty.user.grpc.TokenIntrospectionReq\x1a3.icu.jiapeng.kitty.user.grpc.TokenIntrospectionResp\"\x00\x12p\n" +
	"\rSaTokenDaoGet\x12-.icu.jiapeng.kitty.user.grpc.SaTokenDaoGetReq\x1a..icu.jiapeng.kitty.user.grpc.SaTokenDaoGetResp\"\x00\x12|\n" +
	"\x11SaTokenDaoTimeOut\x121.icu.jiapeng.kitty.user.grpc.SaTokenDaoTimeOutReq\x1a2.icu.jiapeng.kitty.user.grpc.SaTokenDaoTimeOutResp\"\x00B\\\n" +
	" icu.jiapeng.kitty.user.auth.grpcB\x0eAuthServiceSupP\x01Z&kitty-topic/internal/grpcclient/authpbb\x06proto3"

var (
	file_kitty_user_auth_proto_rawDescOnce sync.Once
	file_kitty_user_auth_proto_rawDescData []byte
)

func file_kitty_user_auth_proto_rawDescGZIP() []byte {
	file_kitty_user_auth_proto_rawDescOnce.Do(func() {
		file_kitty_user_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kitty_user_auth_proto_rawDesc), len(file_kitty_user_auth_proto_rawDesc)))
	})
	return file_kitty_user_auth_proto_rawDescData
}

var file_kitty_user_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_kitty_user_auth_proto_goTypes = []any{
	(*TokenIntrospectionReq)(nil),  // 0: icu.jiapeng.kitty.user.grpc.TokenIntrospectionReq
	(*TokenIntrospectionResp)(nil), // 1: icu.jiapeng.kitty.user.grpc.TokenIntrospectionResp
	(*SaTokenDaoGetReq)(nil),       // 2: icu.jiapeng.kitty.user.grpc.SaTokenDaoGetReq
	(*SaTokenDaoGetResp)(nil),      // 3: icu.jiapeng.kitty.user.grpc.SaTokenDaoGetResp
	(*SaTokenDaoTimeOutReq)(nil),   // 4: icu.jiapeng.kitty.user.grpc.SaTokenDaoTimeOutReq
	(*SaTokenDaoTimeOutResp)(nil),  // 5: icu.jiapeng.kitty.user.grpc.SaTokenDaoTimeOutResp
}
var file_kitty_user_auth_proto_depIdxs = []int32{
	0, // 0: icu.jiapeng.kitty.user.grpc.AuthService.TokenIntrospection:input_type -> icu.jiapeng.kitty.user.grpc.TokenIntrospectionReq
	2, // 1: icu.jiapeng.kitty.user.grpc.AuthService.SaTokenDaoGet:input_type -> icu.jiapeng.kitty.user.grpc.SaTokenDaoGetReq
	4, // 2: icu.jiapeng.kitty.user.grpc.AuthService.SaTokenDaoTimeOut:input_type -> icu.jiapeng.kitty.user.grpc.SaTokenDaoTimeOutReq
	1, // 3: icu.jiapeng.kitty.user.grpc.AuthService.TokenIntrospection:output_type -> icu.jiapeng.kitty.user.grpc.TokenIntrospectionResp
	3, // 4: icu.jiapeng.kitty.user.grpc.AuthService.SaTokenDaoGet:output_type -> icu.jiapeng.kitty.user.grpc.SaTokenDaoGetResp
	5, // 5: icu.jiapeng.kitty.user.grpc.AuthService.SaTokenDaoTimeOut:output_type -> icu.jiapeng.kitty.user.grpc.SaTokenDaoTimeOutResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kitty_user_auth_proto_init() }
func file_kitty_user_auth_proto_init() {
	if File_kitty_user_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kitty_user_auth_proto_rawDesc), len(file_kitty_user_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kitty_user_auth_proto_goTypes,
		DependencyIndexes: file_kitty_user_auth_proto_depIdxs,
		MessageInfos:      file_kitty_user_auth_proto_msgTypes,
	}.Build()
	File_kitty_user_auth_proto = out.File
	file_kitty_user_auth_proto_goTypes = nil
	file_kitty_user_auth_proto_depIdxs = nil
}
