// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0--rc2
// source: kitty_user_auth.proto

package authpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthService_TokenIntrospection_FullMethodName = "/icu.jiapeng.kitty.user.grpc.AuthService/TokenIntrospection"
	AuthService_SaTokenDaoGet_FullMethodName      = "/icu.jiapeng.kitty.user.grpc.AuthService/SaTokenDaoGet"
	AuthService_SaTokenDaoTimeOut_FullMethodName  = "/icu.jiapeng.kitty.user.grpc.AuthService/SaTokenDaoTimeOut"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	TokenIntrospection(ctx context.Context, in *TokenIntrospectionReq, opts ...grpc.CallOption) (*TokenIntrospectionResp, error)
	SaTokenDaoGet(ctx context.Context, in *SaTokenDaoGetReq, opts ...grpc.CallOption) (*SaTokenDaoGetResp, error)
	SaTokenDaoTimeOut(ctx context.Context, in *SaTokenDaoTimeOutReq, opts ...grpc.CallOption) (*SaTokenDaoTimeOutResp, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) TokenIntrospection(ctx context.Context, in *TokenIntrospectionReq, opts ...grpc.CallOption) (*TokenIntrospectionResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenIntrospectionResp)
	err := c.cc.Invoke(ctx, AuthService_TokenIntrospection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SaTokenDaoGet(ctx context.Context, in *SaTokenDaoGetReq, opts ...grpc.CallOption) (*SaTokenDaoGetResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaTokenDaoGetResp)
	err := c.cc.Invoke(ctx, AuthService_SaTokenDaoGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SaTokenDaoTimeOut(ctx context.Context, in *SaTokenDaoTimeOutReq, opts ...grpc.CallOption) (*SaTokenDaoTimeOutResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaTokenDaoTimeOutResp)
	err := c.cc.Invoke(ctx, AuthService_SaTokenDaoTimeOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations must embed UnimplementedAuthServiceServer
// for forward compatibility.
type AuthServiceServer interface {
	TokenIntrospection(context.Context, *TokenIntrospectionReq) (*TokenIntrospectionResp, error)
	SaTokenDaoGet(context.Context, *SaTokenDaoGetReq) (*SaTokenDaoGetResp, error)
	SaTokenDaoTimeOut(context.Context, *SaTokenDaoTimeOutReq) (*SaTokenDaoTimeOutResp, error)
	mustEmbedUnimplementedAuthServiceServer()
}

// UnimplementedAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceServer struct{}

func (UnimplementedAuthServiceServer) TokenIntrospection(context.Context, *TokenIntrospectionReq) (*TokenIntrospectionResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TokenIntrospection not implemented")
}
func (UnimplementedAuthServiceServer) SaTokenDaoGet(context.Context, *SaTokenDaoGetReq) (*SaTokenDaoGetResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaTokenDaoGet not implemented")
}
func (UnimplementedAuthServiceServer) SaTokenDaoTimeOut(context.Context, *SaTokenDaoTimeOutReq) (*SaTokenDaoTimeOutResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaTokenDaoTimeOut not implemented")
}
func (UnimplementedAuthServiceServer) mustEmbedUnimplementedAuthServiceServer() {}
func (UnimplementedAuthServiceServer) testEmbeddedByValue()                     {}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_TokenIntrospection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenIntrospectionReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).TokenIntrospection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_TokenIntrospection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).TokenIntrospection(ctx, req.(*TokenIntrospectionReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SaTokenDaoGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaTokenDaoGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SaTokenDaoGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SaTokenDaoGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SaTokenDaoGet(ctx, req.(*SaTokenDaoGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SaTokenDaoTimeOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaTokenDaoTimeOutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SaTokenDaoTimeOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SaTokenDaoTimeOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SaTokenDaoTimeOut(ctx, req.(*SaTokenDaoTimeOutReq))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "icu.jiapeng.kitty.user.grpc.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenIntrospection",
			Handler:    _AuthService_TokenIntrospection_Handler,
		},
		{
			MethodName: "SaTokenDaoGet",
			Handler:    _AuthService_SaTokenDaoGet_Handler,
		},
		{
			MethodName: "SaTokenDaoTimeOut",
			Handler:    _AuthService_SaTokenDaoTimeOut_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kitty_user_auth.proto",
}
