#
# docker build -t test:1.0 ../ -f ./Dockerfile
#

FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/maven:4.0.0-rc-5-amazoncorretto-25-debian AS build

WORKDIR /work
COPY pom.xml pom.xml
COPY kitty-transcoder/pom.xml kitty-transcoder/pom.xml
COPY kitty-transcoder/kitty-transcoder-api/pom.xml kitty-transcoder/kitty-transcoder-api/pom.xml
COPY kitty-transcoder/kitty-transcoder-grpc/pom.xml kitty-transcoder/kitty-transcoder-grpc/pom.xml
COPY kitty-transcoder/kitty-transcoder-func/pom.xml kitty-transcoder/kitty-transcoder-func/pom.xml
COPY kitty-transcoder/kitty-transcoder-server/pom.xml kitty-transcoder/kitty-transcoder-server/pom.xml
RUN mvn dependency:go-offline -f kitty-transcoder/pom.xml

# 全拷贝构建jar
COPY kitty-transcoder kitty-transcoder
RUN mvn -Pprod clean package -DskipTests -f kitty-transcoder/pom.xml

FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/openjdk:25-jdk-slim

LABEL maintainer="jiapeng_aoa@163.com"
LABEL version="1.0"
LABEL description="kitty-transcoder"

COPY --from=build /work/kitty-transcoder/kitty-transcoder-server/target/app.jar /app/app.jar

# 默认端口
EXPOSE 9703 9803
#复制jar包到工作目录
WORKDIR /app


ENTRYPOINT ["java"]

CMD ["-jar", "app.jar"]
