<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>icu.jiapeng</groupId>
        <artifactId>kitty-transcoder</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>kitty-transcoder-server</artifactId>
    <dependencies>
        <!-- 转码服务功能依赖 -->
        <dependency>
            <groupId>icu.jiapeng</groupId>
            <artifactId>kitty-transcoder-func</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
    </dependencies>


    <build>
        <finalName>app</finalName>
        <plugins>
            <plugin>
                <groupId>org.graalvm.buildtools</groupId>
                <artifactId>native-maven-plugin</artifactId>
                <configuration>
                    <mainClass>icu.jiapeng.kitty.transcoder.KittyTranscoderApplication</mainClass>
                    <fallback>false</fallback>
                    <metadataRepository>
                        <enabled>true</enabled>
                    </metadataRepository>
                    <buildArgs>
                        <argument>--enable-url-protocols=http,https</argument>
                        <argument>-H:+SharedArenaSupport</argument>
                    </buildArgs>
                    <agent>
                        <options>
                            <option>config-output-dir=src/main/resources/META-INF/native-image</option>
                            <option>config-write-period-secs=5</option>
                        </options>
                    </agent>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>icu.jiapeng.kitty.transcoder.KittyTranscoderApplication</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.source}</target>
                    <annotationProcessorPaths>
                        <!-- MapStruct -->
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                        <!-- Lombok -->
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>