<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>icu.jiapeng</groupId>
        <artifactId>kittycms</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <packaging>pom</packaging>
    <artifactId>kitty-plugin</artifactId>

    <modules>
        <module>kitty-user-plugin-openfeign-sa</module>
        <module>kitty-oauth2-resource-spring-web</module>
        <module>kitty-oauth2-server-spring-web</module>
    </modules>
</project>