// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0--rc2
// source: topic.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Tags          string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicReq) Reset() {
	*x = CreateTopicReq{}
	mi := &file_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicReq) ProtoMessage() {}

func (x *CreateTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicReq.ProtoReflect.Descriptor instead.
func (*CreateTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTopicReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTopicReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateTopicReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateTopicReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type CreateTopicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResp) Reset() {
	*x = CreateTopicResp{}
	mi := &file_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResp) ProtoMessage() {}

func (x *CreateTopicResp) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResp.ProtoReflect.Descriptor instead.
func (*CreateTopicResp) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicReq) Reset() {
	*x = GetTopicReq{}
	mi := &file_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicReq) ProtoMessage() {}

func (x *GetTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicReq.ProtoReflect.Descriptor instead.
func (*GetTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{2}
}

func (x *GetTopicReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListTopicsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	SearchKey     string                 `protobuf:"bytes,3,opt,name=searchKey,proto3" json:"searchKey,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsReq) Reset() {
	*x = ListTopicsReq{}
	mi := &file_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsReq) ProtoMessage() {}

func (x *ListTopicsReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsReq.ProtoReflect.Descriptor instead.
func (*ListTopicsReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{3}
}

func (x *ListTopicsReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTopicsReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListTopicsReq) GetSearchKey() string {
	if x != nil {
		return x.SearchKey
	}
	return ""
}

func (x *ListTopicsReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListTopicsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*TopicResp           `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResp) Reset() {
	*x = ListTopicsResp{}
	mi := &file_topic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResp) ProtoMessage() {}

func (x *ListTopicsResp) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResp.ProtoReflect.Descriptor instead.
func (*ListTopicsResp) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{4}
}

func (x *ListTopicsResp) GetTopics() []*TopicResp {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ListTopicsResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Tags          string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicReq) Reset() {
	*x = UpdateTopicReq{}
	mi := &file_topic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicReq) ProtoMessage() {}

func (x *UpdateTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicReq.ProtoReflect.Descriptor instead.
func (*UpdateTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTopicReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTopicReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTopicReq) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *UpdateTopicReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateTopicReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type UpdateTopicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicResp) Reset() {
	*x = UpdateTopicResp{}
	mi := &file_topic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicResp) ProtoMessage() {}

func (x *UpdateTopicResp) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicResp.ProtoReflect.Descriptor instead.
func (*UpdateTopicResp) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTopicResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicReq) Reset() {
	*x = DeleteTopicReq{}
	mi := &file_topic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicReq) ProtoMessage() {}

func (x *DeleteTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicReq.ProtoReflect.Descriptor instead.
func (*DeleteTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTopicReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTopicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResp) Reset() {
	*x = DeleteTopicResp{}
	mi := &file_topic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResp) ProtoMessage() {}

func (x *DeleteTopicResp) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResp.ProtoReflect.Descriptor instead.
func (*DeleteTopicResp) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTopicResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubmitTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitTopicReq) Reset() {
	*x = SubmitTopicReq{}
	mi := &file_topic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTopicReq) ProtoMessage() {}

func (x *SubmitTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTopicReq.ProtoReflect.Descriptor instead.
func (*SubmitTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitTopicReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RejectTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTopicReq) Reset() {
	*x = RejectTopicReq{}
	mi := &file_topic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTopicReq) ProtoMessage() {}

func (x *RejectTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTopicReq.ProtoReflect.Descriptor instead.
func (*RejectTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{10}
}

func (x *RejectTopicReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ApproveTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTopicReq) Reset() {
	*x = ApproveTopicReq{}
	mi := &file_topic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTopicReq) ProtoMessage() {}

func (x *ApproveTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTopicReq.ProtoReflect.Descriptor instead.
func (*ApproveTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{11}
}

func (x *ApproveTopicReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PublishTopicReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTopicReq) Reset() {
	*x = PublishTopicReq{}
	mi := &file_topic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTopicReq) ProtoMessage() {}

func (x *PublishTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTopicReq.ProtoReflect.Descriptor instead.
func (*PublishTopicReq) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{12}
}

func (x *PublishTopicReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OperationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResp) Reset() {
	*x = OperationResp{}
	mi := &file_topic_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResp) ProtoMessage() {}

func (x *OperationResp) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResp.ProtoReflect.Descriptor instead.
func (*OperationResp) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{13}
}

func (x *OperationResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TopicResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Tags          string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	PublishedAt   int64                  `protobuf:"varint,7,opt,name=publishedAt,proto3" json:"publishedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,9,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,11,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicResp) Reset() {
	*x = TopicResp{}
	mi := &file_topic_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicResp) ProtoMessage() {}

func (x *TopicResp) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicResp.ProtoReflect.Descriptor instead.
func (*TopicResp) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{14}
}

func (x *TopicResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TopicResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TopicResp) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TopicResp) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TopicResp) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *TopicResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TopicResp) GetPublishedAt() int64 {
	if x != nil {
		return x.PublishedAt
	}
	return 0
}

func (x *TopicResp) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TopicResp) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TopicResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TopicResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_topic_proto protoreflect.FileDescriptor

const file_topic_proto_rawDesc = "" +
	"\n" +
	"\vtopic.proto\x12\x1cicu.jiapeng.kitty.topic.grpc\"l\n" +
	"\x0eCreateTopicReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\"!\n" +
	"\x0fCreateTopicResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1d\n" +
	"\vGetTopicReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"m\n" +
	"\rListTopicsReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1c\n" +
	"\tsearchKey\x18\x03 \x01(\tR\tsearchKey\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"g\n" +
	"\x0eListTopicsResp\x12?\n" +
	"\x06topics\x18\x01 \x03(\v2'.icu.jiapeng.kitty.topic.grpc.TopicRespR\x06topics\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"|\n" +
	"\x0eUpdateTopicReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\"+\n" +
	"\x0fUpdateTopicResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eDeleteTopicReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fDeleteTopicResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\x0eSubmitTopicReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eRejectTopicReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fApproveTopicReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fPublishTopicReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\rOperationResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa9\x02\n" +
	"\tTopicResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12 \n" +
	"\vpublishedAt\x18\a \x01(\x03R\vpublishedAt\x12\x1c\n" +
	"\tcreatedBy\x18\b \x01(\tR\tcreatedBy\x12\x1c\n" +
	"\tupdatedBy\x18\t \x01(\tR\tupdatedBy\x12\x1c\n" +
	"\tcreatedAt\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\v \x01(\x03R\tupdatedAt2\xd9\a\n" +
	"\fTopicService\x12l\n" +
	"\vCreateTopic\x12,.icu.jiapeng.kitty.topic.grpc.CreateTopicReq\x1a-.icu.jiapeng.kitty.topic.grpc.CreateTopicResp\"\x00\x12`\n" +
	"\bGetTopic\x12).icu.jiapeng.kitty.topic.grpc.GetTopicReq\x1a'.icu.jiapeng.kitty.topic.grpc.TopicResp\"\x00\x12i\n" +
	"\n" +
	"ListTopics\x12+.icu.jiapeng.kitty.topic.grpc.ListTopicsReq\x1a,.icu.jiapeng.kitty.topic.grpc.ListTopicsResp\"\x00\x12l\n" +
	"\vUpdateTopic\x12,.icu.jiapeng.kitty.topic.grpc.UpdateTopicReq\x1a-.icu.jiapeng.kitty.topic.grpc.UpdateTopicResp\"\x00\x12l\n" +
	"\vDeleteTopic\x12,.icu.jiapeng.kitty.topic.grpc.DeleteTopicReq\x1a-.icu.jiapeng.kitty.topic.grpc.DeleteTopicResp\"\x00\x12j\n" +
	"\vSubmitTopic\x12,.icu.jiapeng.kitty.topic.grpc.SubmitTopicReq\x1a+.icu.jiapeng.kitty.topic.grpc.OperationResp\"\x00\x12j\n" +
	"\vRejectTopic\x12,.icu.jiapeng.kitty.topic.grpc.RejectTopicReq\x1a+.icu.jiapeng.kitty.topic.grpc.OperationResp\"\x00\x12l\n" +
	"\fApproveTopic\x12-.icu.jiapeng.kitty.topic.grpc.ApproveTopicReq\x1a+.icu.jiapeng.kitty.topic.grpc.OperationResp\"\x00\x12l\n" +
	"\fPublishTopic\x12-.icu.jiapeng.kitty.topic.grpc.PublishTopicReq\x1a+.icu.jiapeng.kitty.topic.grpc.OperationResp\"\x00BN\n" +
	"\x1cicu.jiapeng.kitty.topic.grpcB\x0fTopicServiceSupP\x01Z\x1bkitty-topic/internal/grpcpbb\x06proto3"

var (
	file_topic_proto_rawDescOnce sync.Once
	file_topic_proto_rawDescData []byte
)

func file_topic_proto_rawDescGZIP() []byte {
	file_topic_proto_rawDescOnce.Do(func() {
		file_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topic_proto_rawDesc), len(file_topic_proto_rawDesc)))
	})
	return file_topic_proto_rawDescData
}

var file_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_topic_proto_goTypes = []any{
	(*CreateTopicReq)(nil),  // 0: icu.jiapeng.kitty.topic.grpc.CreateTopicReq
	(*CreateTopicResp)(nil), // 1: icu.jiapeng.kitty.topic.grpc.CreateTopicResp
	(*GetTopicReq)(nil),     // 2: icu.jiapeng.kitty.topic.grpc.GetTopicReq
	(*ListTopicsReq)(nil),   // 3: icu.jiapeng.kitty.topic.grpc.ListTopicsReq
	(*ListTopicsResp)(nil),  // 4: icu.jiapeng.kitty.topic.grpc.ListTopicsResp
	(*UpdateTopicReq)(nil),  // 5: icu.jiapeng.kitty.topic.grpc.UpdateTopicReq
	(*UpdateTopicResp)(nil), // 6: icu.jiapeng.kitty.topic.grpc.UpdateTopicResp
	(*DeleteTopicReq)(nil),  // 7: icu.jiapeng.kitty.topic.grpc.DeleteTopicReq
	(*DeleteTopicResp)(nil), // 8: icu.jiapeng.kitty.topic.grpc.DeleteTopicResp
	(*SubmitTopicReq)(nil),  // 9: icu.jiapeng.kitty.topic.grpc.SubmitTopicReq
	(*RejectTopicReq)(nil),  // 10: icu.jiapeng.kitty.topic.grpc.RejectTopicReq
	(*ApproveTopicReq)(nil), // 11: icu.jiapeng.kitty.topic.grpc.ApproveTopicReq
	(*PublishTopicReq)(nil), // 12: icu.jiapeng.kitty.topic.grpc.PublishTopicReq
	(*OperationResp)(nil),   // 13: icu.jiapeng.kitty.topic.grpc.OperationResp
	(*TopicResp)(nil),       // 14: icu.jiapeng.kitty.topic.grpc.TopicResp
}
var file_topic_proto_depIdxs = []int32{
	14, // 0: icu.jiapeng.kitty.topic.grpc.ListTopicsResp.topics:type_name -> icu.jiapeng.kitty.topic.grpc.TopicResp
	0,  // 1: icu.jiapeng.kitty.topic.grpc.TopicService.CreateTopic:input_type -> icu.jiapeng.kitty.topic.grpc.CreateTopicReq
	2,  // 2: icu.jiapeng.kitty.topic.grpc.TopicService.GetTopic:input_type -> icu.jiapeng.kitty.topic.grpc.GetTopicReq
	3,  // 3: icu.jiapeng.kitty.topic.grpc.TopicService.ListTopics:input_type -> icu.jiapeng.kitty.topic.grpc.ListTopicsReq
	5,  // 4: icu.jiapeng.kitty.topic.grpc.TopicService.UpdateTopic:input_type -> icu.jiapeng.kitty.topic.grpc.UpdateTopicReq
	7,  // 5: icu.jiapeng.kitty.topic.grpc.TopicService.DeleteTopic:input_type -> icu.jiapeng.kitty.topic.grpc.DeleteTopicReq
	9,  // 6: icu.jiapeng.kitty.topic.grpc.TopicService.SubmitTopic:input_type -> icu.jiapeng.kitty.topic.grpc.SubmitTopicReq
	10, // 7: icu.jiapeng.kitty.topic.grpc.TopicService.RejectTopic:input_type -> icu.jiapeng.kitty.topic.grpc.RejectTopicReq
	11, // 8: icu.jiapeng.kitty.topic.grpc.TopicService.ApproveTopic:input_type -> icu.jiapeng.kitty.topic.grpc.ApproveTopicReq
	12, // 9: icu.jiapeng.kitty.topic.grpc.TopicService.PublishTopic:input_type -> icu.jiapeng.kitty.topic.grpc.PublishTopicReq
	1,  // 10: icu.jiapeng.kitty.topic.grpc.TopicService.CreateTopic:output_type -> icu.jiapeng.kitty.topic.grpc.CreateTopicResp
	14, // 11: icu.jiapeng.kitty.topic.grpc.TopicService.GetTopic:output_type -> icu.jiapeng.kitty.topic.grpc.TopicResp
	4,  // 12: icu.jiapeng.kitty.topic.grpc.TopicService.ListTopics:output_type -> icu.jiapeng.kitty.topic.grpc.ListTopicsResp
	6,  // 13: icu.jiapeng.kitty.topic.grpc.TopicService.UpdateTopic:output_type -> icu.jiapeng.kitty.topic.grpc.UpdateTopicResp
	8,  // 14: icu.jiapeng.kitty.topic.grpc.TopicService.DeleteTopic:output_type -> icu.jiapeng.kitty.topic.grpc.DeleteTopicResp
	13, // 15: icu.jiapeng.kitty.topic.grpc.TopicService.SubmitTopic:output_type -> icu.jiapeng.kitty.topic.grpc.OperationResp
	13, // 16: icu.jiapeng.kitty.topic.grpc.TopicService.RejectTopic:output_type -> icu.jiapeng.kitty.topic.grpc.OperationResp
	13, // 17: icu.jiapeng.kitty.topic.grpc.TopicService.ApproveTopic:output_type -> icu.jiapeng.kitty.topic.grpc.OperationResp
	13, // 18: icu.jiapeng.kitty.topic.grpc.TopicService.PublishTopic:output_type -> icu.jiapeng.kitty.topic.grpc.OperationResp
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_topic_proto_init() }
func file_topic_proto_init() {
	if File_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topic_proto_rawDesc), len(file_topic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topic_proto_goTypes,
		DependencyIndexes: file_topic_proto_depIdxs,
		MessageInfos:      file_topic_proto_msgTypes,
	}.Build()
	File_topic_proto = out.File
	file_topic_proto_goTypes = nil
	file_topic_proto_depIdxs = nil
}
