quarkus.application.name=kitty-click-qk
quarkus.application.version=1.0.0
quarkus.mongodb.connection-string=mongodb://127.0.0.1:27017
quarkus.mongodb.database=kitty_click_qk
quarkus.jackson.fail-on-unknown-properties=false
quarkus.http.port=9707
quarkus.redis.hosts=redis://127.0.0.1:6379
quarkus.redis.password=123456
quarkus.redis.max-pool-size=32

# Ak/Sk \u7F13\u5B58 TTL\uFF08\u79D2\uFF09
kittyclick.cache.aksk-ttl-seconds=3600

# \u5F02\u6B65\u4E0A\u62A5\uFF1A\u5B9A\u65F6\u5237\u5165 Mongo \u7684\u95F4\u9694\u4E0E\u6279\u91CF
kittyclick.report.flush.batch-size=1000