// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0--rc2
// source: transcode.proto

package grpcpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTaskReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InputType         string                 `protobuf:"bytes,1,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputPath         string                 `protobuf:"bytes,2,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	StrategyId        int64                  `protobuf:"varint,3,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	Priority          int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	WatermarkUrl      string                 `protobuf:"bytes,5,opt,name=watermark_url,json=watermarkUrl,proto3" json:"watermark_url,omitempty"`
	WatermarkPosition string                 `protobuf:"bytes,6,opt,name=watermark_position,json=watermarkPosition,proto3" json:"watermark_position,omitempty"`
	Notifications     []*NotificationConfig  `protobuf:"bytes,7,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateTaskReq) Reset() {
	*x = CreateTaskReq{}
	mi := &file_transcode_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskReq) ProtoMessage() {}

func (x *CreateTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskReq.ProtoReflect.Descriptor instead.
func (*CreateTaskReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskReq) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *CreateTaskReq) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *CreateTaskReq) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *CreateTaskReq) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskReq) GetWatermarkUrl() string {
	if x != nil {
		return x.WatermarkUrl
	}
	return ""
}

func (x *CreateTaskReq) GetWatermarkPosition() string {
	if x != nil {
		return x.WatermarkPosition
	}
	return ""
}

func (x *CreateTaskReq) GetNotifications() []*NotificationConfig {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type NotificationConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationConfig) Reset() {
	*x = NotificationConfig{}
	mi := &file_transcode_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationConfig) ProtoMessage() {}

func (x *NotificationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationConfig.ProtoReflect.Descriptor instead.
func (*NotificationConfig) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NotificationConfig) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type CreateTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResp) Reset() {
	*x = CreateTaskResp{}
	mi := &file_transcode_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResp) ProtoMessage() {}

func (x *CreateTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResp.ProtoReflect.Descriptor instead.
func (*CreateTaskResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskReq) Reset() {
	*x = GetTaskReq{}
	mi := &file_transcode_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskReq) ProtoMessage() {}

func (x *GetTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskReq.ProtoReflect.Descriptor instead.
func (*GetTaskReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	InputType     string                 `protobuf:"bytes,4,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputPath     string                 `protobuf:"bytes,5,opt,name=input_path,json=inputPath,proto3" json:"input_path,omitempty"`
	OutputPath    string                 `protobuf:"bytes,6,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	OutputHttpUrl string                 `protobuf:"bytes,7,opt,name=output_http_url,json=outputHttpUrl,proto3" json:"output_http_url,omitempty"`
	StrategyId    int64                  `protobuf:"varint,8,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   int64                  `protobuf:"varint,12,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResp) Reset() {
	*x = TaskResp{}
	mi := &file_transcode_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResp) ProtoMessage() {}

func (x *TaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResp.ProtoReflect.Descriptor instead.
func (*TaskResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResp) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TaskResp) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *TaskResp) GetInputPath() string {
	if x != nil {
		return x.InputPath
	}
	return ""
}

func (x *TaskResp) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *TaskResp) GetOutputHttpUrl() string {
	if x != nil {
		return x.OutputHttpUrl
	}
	return ""
}

func (x *TaskResp) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

func (x *TaskResp) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *TaskResp) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *TaskResp) GetCompletedAt() int64 {
	if x != nil {
		return x.CompletedAt
	}
	return 0
}

type ListTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	TaskType      string                 `protobuf:"bytes,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksReq) Reset() {
	*x = ListTasksReq{}
	mi := &file_transcode_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksReq) ProtoMessage() {}

func (x *ListTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksReq.ProtoReflect.Descriptor instead.
func (*ListTasksReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{5}
}

func (x *ListTasksReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTasksReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListTasksReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListTasksReq) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

type ListTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskResp            `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResp) Reset() {
	*x = ListTasksResp{}
	mi := &file_transcode_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResp) ProtoMessage() {}

func (x *ListTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResp.ProtoReflect.Descriptor instead.
func (*ListTasksResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksResp) GetTasks() []*TaskResp {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskReq) Reset() {
	*x = CancelTaskReq{}
	mi := &file_transcode_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskReq) ProtoMessage() {}

func (x *CancelTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskReq.ProtoReflect.Descriptor instead.
func (*CancelTaskReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{7}
}

func (x *CancelTaskReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResp) Reset() {
	*x = CancelTaskResp{}
	mi := &file_transcode_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResp) ProtoMessage() {}

func (x *CancelTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResp.ProtoReflect.Descriptor instead.
func (*CancelTaskResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTaskResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetProgressReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressReq) Reset() {
	*x = GetProgressReq{}
	mi := &file_transcode_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressReq) ProtoMessage() {}

func (x *GetProgressReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressReq.ProtoReflect.Descriptor instead.
func (*GetProgressReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{9}
}

func (x *GetProgressReq) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ProgressResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressResp) Reset() {
	*x = ProgressResp{}
	mi := &file_transcode_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResp) ProtoMessage() {}

func (x *ProgressResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResp.ProtoReflect.Descriptor instead.
func (*ProgressResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{10}
}

func (x *ProgressResp) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ProgressResp) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ProgressResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStrategiesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategiesReq) Reset() {
	*x = GetStrategiesReq{}
	mi := &file_transcode_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategiesReq) ProtoMessage() {}

func (x *GetStrategiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategiesReq.ProtoReflect.Descriptor instead.
func (*GetStrategiesReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{11}
}

type StrategySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategySummary) Reset() {
	*x = StrategySummary{}
	mi := &file_transcode_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategySummary) ProtoMessage() {}

func (x *StrategySummary) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategySummary.ProtoReflect.Descriptor instead.
func (*StrategySummary) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{12}
}

func (x *StrategySummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StrategySummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetStrategiesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategies    []*StrategySummary     `protobuf:"bytes,1,rep,name=strategies,proto3" json:"strategies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategiesResp) Reset() {
	*x = GetStrategiesResp{}
	mi := &file_transcode_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategiesResp) ProtoMessage() {}

func (x *GetStrategiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategiesResp.ProtoReflect.Descriptor instead.
func (*GetStrategiesResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{13}
}

func (x *GetStrategiesResp) GetStrategies() []*StrategySummary {
	if x != nil {
		return x.Strategies
	}
	return nil
}

type GetStrategyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStrategyReq) Reset() {
	*x = GetStrategyReq{}
	mi := &file_transcode_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStrategyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyReq) ProtoMessage() {}

func (x *GetStrategyReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyReq.ProtoReflect.Descriptor instead.
func (*GetStrategyReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{14}
}

func (x *GetStrategyReq) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type StrategyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Steps         []*StrategyStepDto     `protobuf:"bytes,3,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyResp) Reset() {
	*x = StrategyResp{}
	mi := &file_transcode_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyResp) ProtoMessage() {}

func (x *StrategyResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyResp.ProtoReflect.Descriptor instead.
func (*StrategyResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{15}
}

func (x *StrategyResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StrategyResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyResp) GetSteps() []*StrategyStepDto {
	if x != nil {
		return x.Steps
	}
	return nil
}

type StrategyStepDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        int32                  `protobuf:"varint,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Depends       string                 `protobuf:"bytes,3,opt,name=depends,proto3" json:"depends,omitempty"`
	Param         string                 `protobuf:"bytes,4,opt,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyStepDto) Reset() {
	*x = StrategyStepDto{}
	mi := &file_transcode_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyStepDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyStepDto) ProtoMessage() {}

func (x *StrategyStepDto) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyStepDto.ProtoReflect.Descriptor instead.
func (*StrategyStepDto) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{16}
}

func (x *StrategyStepDto) GetStepId() int32 {
	if x != nil {
		return x.StepId
	}
	return 0
}

func (x *StrategyStepDto) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StrategyStepDto) GetDepends() string {
	if x != nil {
		return x.Depends
	}
	return ""
}

func (x *StrategyStepDto) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

type CreateStrategyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Steps         []*StrategyStepDto     `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyReq) Reset() {
	*x = CreateStrategyReq{}
	mi := &file_transcode_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStrategyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStrategyReq) ProtoMessage() {}

func (x *CreateStrategyReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyReq.ProtoReflect.Descriptor instead.
func (*CreateStrategyReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{17}
}

func (x *CreateStrategyReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStrategyReq) GetSteps() []*StrategyStepDto {
	if x != nil {
		return x.Steps
	}
	return nil
}

type CreateStrategyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStrategyResp) Reset() {
	*x = CreateStrategyResp{}
	mi := &file_transcode_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStrategyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStrategyResp) ProtoMessage() {}

func (x *CreateStrategyResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStrategyResp.ProtoReflect.Descriptor instead.
func (*CreateStrategyResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{18}
}

func (x *CreateStrategyResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteStrategyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyId    int64                  `protobuf:"varint,1,opt,name=strategy_id,json=strategyId,proto3" json:"strategy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyReq) Reset() {
	*x = DeleteStrategyReq{}
	mi := &file_transcode_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStrategyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStrategyReq) ProtoMessage() {}

func (x *DeleteStrategyReq) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStrategyReq.ProtoReflect.Descriptor instead.
func (*DeleteStrategyReq) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteStrategyReq) GetStrategyId() int64 {
	if x != nil {
		return x.StrategyId
	}
	return 0
}

type DeleteStrategyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStrategyResp) Reset() {
	*x = DeleteStrategyResp{}
	mi := &file_transcode_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStrategyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStrategyResp) ProtoMessage() {}

func (x *DeleteStrategyResp) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStrategyResp.ProtoReflect.Descriptor instead.
func (*DeleteStrategyResp) Descriptor() ([]byte, []int) {
	return file_transcode_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteStrategyResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_transcode_proto protoreflect.FileDescriptor

const file_transcode_proto_rawDesc = "" +
	"\n" +
	"\x0ftranscode.proto\x12\n" +
	"transcoder\"\xa4\x02\n" +
	"\rCreateTaskReq\x12\x1d\n" +
	"\n" +
	"input_type\x18\x01 \x01(\tR\tinputType\x12\x1d\n" +
	"\n" +
	"input_path\x18\x02 \x01(\tR\tinputPath\x12\x1f\n" +
	"\vstrategy_id\x18\x03 \x01(\x03R\n" +
	"strategyId\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12#\n" +
	"\rwatermark_url\x18\x05 \x01(\tR\fwatermarkUrl\x12-\n" +
	"\x12watermark_position\x18\x06 \x01(\tR\x11watermarkPosition\x12D\n" +
	"\rnotifications\x18\a \x03(\v2\x1e.transcoder.NotificationConfigR\rnotifications\"D\n" +
	"\x12NotificationConfig\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\")\n" +
	"\x0eCreateTaskResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"%\n" +
	"\n" +
	"GetTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\xfc\x02\n" +
	"\bTaskResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x1d\n" +
	"\n" +
	"input_type\x18\x04 \x01(\tR\tinputType\x12\x1d\n" +
	"\n" +
	"input_path\x18\x05 \x01(\tR\tinputPath\x12\x1f\n" +
	"\voutput_path\x18\x06 \x01(\tR\n" +
	"outputPath\x12&\n" +
	"\x0foutput_http_url\x18\a \x01(\tR\routputHttpUrl\x12\x1f\n" +
	"\vstrategy_id\x18\b \x01(\x03R\n" +
	"strategyId\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\x03R\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\f \x01(\x03R\vcompletedAt\"k\n" +
	"\fListTasksReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\tR\btaskType\"Q\n" +
	"\rListTasksResp\x12*\n" +
	"\x05tasks\x18\x01 \x03(\v2\x14.transcoder.TaskRespR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"(\n" +
	"\rCancelTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"*\n" +
	"\x0eCancelTaskResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\")\n" +
	"\x0eGetProgressReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"[\n" +
	"\fProgressResp\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\x12\n" +
	"\x10GetStrategiesReq\"5\n" +
	"\x0fStrategySummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"P\n" +
	"\x11GetStrategiesResp\x12;\n" +
	"\n" +
	"strategies\x18\x01 \x03(\v2\x1b.transcoder.StrategySummaryR\n" +
	"strategies\"1\n" +
	"\x0eGetStrategyReq\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\"e\n" +
	"\fStrategyResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x05steps\x18\x03 \x03(\v2\x1b.transcoder.StrategyStepDtoR\x05steps\"n\n" +
	"\x0fStrategyStepDto\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\x05R\x06stepId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\adepends\x18\x03 \x01(\tR\adepends\x12\x14\n" +
	"\x05param\x18\x04 \x01(\tR\x05param\"Z\n" +
	"\x11CreateStrategyReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x05steps\x18\x02 \x03(\v2\x1b.transcoder.StrategyStepDtoR\x05steps\"$\n" +
	"\x12CreateStrategyResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x11DeleteStrategyReq\x12\x1f\n" +
	"\vstrategy_id\x18\x01 \x01(\x03R\n" +
	"strategyId\".\n" +
	"\x12DeleteStrategyResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x91\x05\n" +
	"\x10TranscodeService\x12C\n" +
	"\n" +
	"CreateTask\x12\x19.transcoder.CreateTaskReq\x1a\x1a.transcoder.CreateTaskResp\x127\n" +
	"\aGetTask\x12\x16.transcoder.GetTaskReq\x1a\x14.transcoder.TaskResp\x12@\n" +
	"\tListTasks\x12\x18.transcoder.ListTasksReq\x1a\x19.transcoder.ListTasksResp\x12C\n" +
	"\n" +
	"CancelTask\x12\x19.transcoder.CancelTaskReq\x1a\x1a.transcoder.CancelTaskResp\x12C\n" +
	"\vGetProgress\x12\x1a.transcoder.GetProgressReq\x1a\x18.transcoder.ProgressResp\x12L\n" +
	"\rGetStrategies\x12\x1c.transcoder.GetStrategiesReq\x1a\x1d.transcoder.GetStrategiesResp\x12C\n" +
	"\vGetStrategy\x12\x1a.transcoder.GetStrategyReq\x1a\x18.transcoder.StrategyResp\x12O\n" +
	"\x0eCreateStrategy\x12\x1d.transcoder.CreateStrategyReq\x1a\x1e.transcoder.CreateStrategyResp\x12O\n" +
	"\x0eDeleteStrategy\x12\x1d.transcoder.DeleteStrategyReq\x1a\x1e.transcoder.DeleteStrategyRespB%Z#kitty-transcoder-go/internal/grpcpbb\x06proto3"

var (
	file_transcode_proto_rawDescOnce sync.Once
	file_transcode_proto_rawDescData []byte
)

func file_transcode_proto_rawDescGZIP() []byte {
	file_transcode_proto_rawDescOnce.Do(func() {
		file_transcode_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcode_proto_rawDesc), len(file_transcode_proto_rawDesc)))
	})
	return file_transcode_proto_rawDescData
}

var file_transcode_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_transcode_proto_goTypes = []any{
	(*CreateTaskReq)(nil),      // 0: transcoder.CreateTaskReq
	(*NotificationConfig)(nil), // 1: transcoder.NotificationConfig
	(*CreateTaskResp)(nil),     // 2: transcoder.CreateTaskResp
	(*GetTaskReq)(nil),         // 3: transcoder.GetTaskReq
	(*TaskResp)(nil),           // 4: transcoder.TaskResp
	(*ListTasksReq)(nil),       // 5: transcoder.ListTasksReq
	(*ListTasksResp)(nil),      // 6: transcoder.ListTasksResp
	(*CancelTaskReq)(nil),      // 7: transcoder.CancelTaskReq
	(*CancelTaskResp)(nil),     // 8: transcoder.CancelTaskResp
	(*GetProgressReq)(nil),     // 9: transcoder.GetProgressReq
	(*ProgressResp)(nil),       // 10: transcoder.ProgressResp
	(*GetStrategiesReq)(nil),   // 11: transcoder.GetStrategiesReq
	(*StrategySummary)(nil),    // 12: transcoder.StrategySummary
	(*GetStrategiesResp)(nil),  // 13: transcoder.GetStrategiesResp
	(*GetStrategyReq)(nil),     // 14: transcoder.GetStrategyReq
	(*StrategyResp)(nil),       // 15: transcoder.StrategyResp
	(*StrategyStepDto)(nil),    // 16: transcoder.StrategyStepDto
	(*CreateStrategyReq)(nil),  // 17: transcoder.CreateStrategyReq
	(*CreateStrategyResp)(nil), // 18: transcoder.CreateStrategyResp
	(*DeleteStrategyReq)(nil),  // 19: transcoder.DeleteStrategyReq
	(*DeleteStrategyResp)(nil), // 20: transcoder.DeleteStrategyResp
}
var file_transcode_proto_depIdxs = []int32{
	1,  // 0: transcoder.CreateTaskReq.notifications:type_name -> transcoder.NotificationConfig
	4,  // 1: transcoder.ListTasksResp.tasks:type_name -> transcoder.TaskResp
	12, // 2: transcoder.GetStrategiesResp.strategies:type_name -> transcoder.StrategySummary
	16, // 3: transcoder.StrategyResp.steps:type_name -> transcoder.StrategyStepDto
	16, // 4: transcoder.CreateStrategyReq.steps:type_name -> transcoder.StrategyStepDto
	0,  // 5: transcoder.TranscodeService.CreateTask:input_type -> transcoder.CreateTaskReq
	3,  // 6: transcoder.TranscodeService.GetTask:input_type -> transcoder.GetTaskReq
	5,  // 7: transcoder.TranscodeService.ListTasks:input_type -> transcoder.ListTasksReq
	7,  // 8: transcoder.TranscodeService.CancelTask:input_type -> transcoder.CancelTaskReq
	9,  // 9: transcoder.TranscodeService.GetProgress:input_type -> transcoder.GetProgressReq
	11, // 10: transcoder.TranscodeService.GetStrategies:input_type -> transcoder.GetStrategiesReq
	14, // 11: transcoder.TranscodeService.GetStrategy:input_type -> transcoder.GetStrategyReq
	17, // 12: transcoder.TranscodeService.CreateStrategy:input_type -> transcoder.CreateStrategyReq
	19, // 13: transcoder.TranscodeService.DeleteStrategy:input_type -> transcoder.DeleteStrategyReq
	2,  // 14: transcoder.TranscodeService.CreateTask:output_type -> transcoder.CreateTaskResp
	4,  // 15: transcoder.TranscodeService.GetTask:output_type -> transcoder.TaskResp
	6,  // 16: transcoder.TranscodeService.ListTasks:output_type -> transcoder.ListTasksResp
	8,  // 17: transcoder.TranscodeService.CancelTask:output_type -> transcoder.CancelTaskResp
	10, // 18: transcoder.TranscodeService.GetProgress:output_type -> transcoder.ProgressResp
	13, // 19: transcoder.TranscodeService.GetStrategies:output_type -> transcoder.GetStrategiesResp
	15, // 20: transcoder.TranscodeService.GetStrategy:output_type -> transcoder.StrategyResp
	18, // 21: transcoder.TranscodeService.CreateStrategy:output_type -> transcoder.CreateStrategyResp
	20, // 22: transcoder.TranscodeService.DeleteStrategy:output_type -> transcoder.DeleteStrategyResp
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_transcode_proto_init() }
func file_transcode_proto_init() {
	if File_transcode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcode_proto_rawDesc), len(file_transcode_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transcode_proto_goTypes,
		DependencyIndexes: file_transcode_proto_depIdxs,
		MessageInfos:      file_transcode_proto_msgTypes,
	}.Build()
	File_transcode_proto = out.File
	file_transcode_proto_goTypes = nil
	file_transcode_proto_depIdxs = nil
}
