// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0--rc2
// source: transcode.proto

package grpcpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranscodeService_CreateTask_FullMethodName     = "/transcoder.TranscodeService/CreateTask"
	TranscodeService_GetTask_FullMethodName        = "/transcoder.TranscodeService/GetTask"
	TranscodeService_ListTasks_FullMethodName      = "/transcoder.TranscodeService/ListTasks"
	TranscodeService_CancelTask_FullMethodName     = "/transcoder.TranscodeService/CancelTask"
	TranscodeService_GetProgress_FullMethodName    = "/transcoder.TranscodeService/GetProgress"
	TranscodeService_GetStrategies_FullMethodName  = "/transcoder.TranscodeService/GetStrategies"
	TranscodeService_GetStrategy_FullMethodName    = "/transcoder.TranscodeService/GetStrategy"
	TranscodeService_CreateStrategy_FullMethodName = "/transcoder.TranscodeService/CreateStrategy"
	TranscodeService_DeleteStrategy_FullMethodName = "/transcoder.TranscodeService/DeleteStrategy"
)

// TranscodeServiceClient is the client API for TranscodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 转码服务：任务、策略、进度（与 Java TranscodeService 对齐）
type TranscodeServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error)
	GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*TaskResp, error)
	ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error)
	CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*CancelTaskResp, error)
	GetProgress(ctx context.Context, in *GetProgressReq, opts ...grpc.CallOption) (*ProgressResp, error)
	GetStrategies(ctx context.Context, in *GetStrategiesReq, opts ...grpc.CallOption) (*GetStrategiesResp, error)
	GetStrategy(ctx context.Context, in *GetStrategyReq, opts ...grpc.CallOption) (*StrategyResp, error)
	CreateStrategy(ctx context.Context, in *CreateStrategyReq, opts ...grpc.CallOption) (*CreateStrategyResp, error)
	DeleteStrategy(ctx context.Context, in *DeleteStrategyReq, opts ...grpc.CallOption) (*DeleteStrategyResp, error)
}

type transcodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscodeServiceClient(cc grpc.ClientConnInterface) TranscodeServiceClient {
	return &transcodeServiceClient{cc}
}

func (c *transcodeServiceClient) CreateTask(ctx context.Context, in *CreateTaskReq, opts ...grpc.CallOption) (*CreateTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResp)
	err := c.cc.Invoke(ctx, TranscodeService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetTask(ctx context.Context, in *GetTaskReq, opts ...grpc.CallOption) (*TaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResp)
	err := c.cc.Invoke(ctx, TranscodeService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) ListTasks(ctx context.Context, in *ListTasksReq, opts ...grpc.CallOption) (*ListTasksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResp)
	err := c.cc.Invoke(ctx, TranscodeService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) CancelTask(ctx context.Context, in *CancelTaskReq, opts ...grpc.CallOption) (*CancelTaskResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResp)
	err := c.cc.Invoke(ctx, TranscodeService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetProgress(ctx context.Context, in *GetProgressReq, opts ...grpc.CallOption) (*ProgressResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgressResp)
	err := c.cc.Invoke(ctx, TranscodeService_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetStrategies(ctx context.Context, in *GetStrategiesReq, opts ...grpc.CallOption) (*GetStrategiesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStrategiesResp)
	err := c.cc.Invoke(ctx, TranscodeService_GetStrategies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) GetStrategy(ctx context.Context, in *GetStrategyReq, opts ...grpc.CallOption) (*StrategyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StrategyResp)
	err := c.cc.Invoke(ctx, TranscodeService_GetStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) CreateStrategy(ctx context.Context, in *CreateStrategyReq, opts ...grpc.CallOption) (*CreateStrategyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStrategyResp)
	err := c.cc.Invoke(ctx, TranscodeService_CreateStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transcodeServiceClient) DeleteStrategy(ctx context.Context, in *DeleteStrategyReq, opts ...grpc.CallOption) (*DeleteStrategyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStrategyResp)
	err := c.cc.Invoke(ctx, TranscodeService_DeleteStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscodeServiceServer is the server API for TranscodeService service.
// All implementations must embed UnimplementedTranscodeServiceServer
// for forward compatibility.
//
// 转码服务：任务、策略、进度（与 Java TranscodeService 对齐）
type TranscodeServiceServer interface {
	CreateTask(context.Context, *CreateTaskReq) (*CreateTaskResp, error)
	GetTask(context.Context, *GetTaskReq) (*TaskResp, error)
	ListTasks(context.Context, *ListTasksReq) (*ListTasksResp, error)
	CancelTask(context.Context, *CancelTaskReq) (*CancelTaskResp, error)
	GetProgress(context.Context, *GetProgressReq) (*ProgressResp, error)
	GetStrategies(context.Context, *GetStrategiesReq) (*GetStrategiesResp, error)
	GetStrategy(context.Context, *GetStrategyReq) (*StrategyResp, error)
	CreateStrategy(context.Context, *CreateStrategyReq) (*CreateStrategyResp, error)
	DeleteStrategy(context.Context, *DeleteStrategyReq) (*DeleteStrategyResp, error)
	mustEmbedUnimplementedTranscodeServiceServer()
}

// UnimplementedTranscodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscodeServiceServer struct{}

func (UnimplementedTranscodeServiceServer) CreateTask(context.Context, *CreateTaskReq) (*CreateTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTranscodeServiceServer) GetTask(context.Context, *GetTaskReq) (*TaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTranscodeServiceServer) ListTasks(context.Context, *ListTasksReq) (*ListTasksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTranscodeServiceServer) CancelTask(context.Context, *CancelTaskReq) (*CancelTaskResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedTranscodeServiceServer) GetProgress(context.Context, *GetProgressReq) (*ProgressResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedTranscodeServiceServer) GetStrategies(context.Context, *GetStrategiesReq) (*GetStrategiesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrategies not implemented")
}
func (UnimplementedTranscodeServiceServer) GetStrategy(context.Context, *GetStrategyReq) (*StrategyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStrategy not implemented")
}
func (UnimplementedTranscodeServiceServer) CreateStrategy(context.Context, *CreateStrategyReq) (*CreateStrategyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStrategy not implemented")
}
func (UnimplementedTranscodeServiceServer) DeleteStrategy(context.Context, *DeleteStrategyReq) (*DeleteStrategyResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStrategy not implemented")
}
func (UnimplementedTranscodeServiceServer) mustEmbedUnimplementedTranscodeServiceServer() {}
func (UnimplementedTranscodeServiceServer) testEmbeddedByValue()                          {}

// UnsafeTranscodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscodeServiceServer will
// result in compilation errors.
type UnsafeTranscodeServiceServer interface {
	mustEmbedUnimplementedTranscodeServiceServer()
}

func RegisterTranscodeServiceServer(s grpc.ServiceRegistrar, srv TranscodeServiceServer) {
	// If the following call panics, it indicates UnimplementedTranscodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranscodeService_ServiceDesc, srv)
}

func _TranscodeService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).CreateTask(ctx, req.(*CreateTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetTask(ctx, req.(*GetTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).ListTasks(ctx, req.(*ListTasksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).CancelTask(ctx, req.(*CancelTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetProgress(ctx, req.(*GetProgressReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetStrategies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetStrategies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetStrategies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetStrategies(ctx, req.(*GetStrategiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_GetStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).GetStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_GetStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).GetStrategy(ctx, req.(*GetStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_CreateStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).CreateStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_CreateStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).CreateStrategy(ctx, req.(*CreateStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TranscodeService_DeleteStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStrategyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServiceServer).DeleteStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TranscodeService_DeleteStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServiceServer).DeleteStrategy(ctx, req.(*DeleteStrategyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TranscodeService_ServiceDesc is the grpc.ServiceDesc for TranscodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranscodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcoder.TranscodeService",
	HandlerType: (*TranscodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TranscodeService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TranscodeService_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TranscodeService_ListTasks_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _TranscodeService_CancelTask_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _TranscodeService_GetProgress_Handler,
		},
		{
			MethodName: "GetStrategies",
			Handler:    _TranscodeService_GetStrategies_Handler,
		},
		{
			MethodName: "GetStrategy",
			Handler:    _TranscodeService_GetStrategy_Handler,
		},
		{
			MethodName: "CreateStrategy",
			Handler:    _TranscodeService_CreateStrategy_Handler,
		},
		{
			MethodName: "DeleteStrategy",
			Handler:    _TranscodeService_DeleteStrategy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transcode.proto",
}
